from .slot_i import SlotI
from .slot_ii import SlotII
from .slot_iii import SlotIII
from .slot_iv import SlotIV
from .slot_v import SlotV
from .slot_vi import SlotVI
from .slot_vii import SlotVII
from .slot_viii import SlotVIII
from .slot_ix import SlotIX
from .slot_x import SlotX